services:
  ollama:
    image: langchain4j/ollama-codellama
    expose:
      - 11434/tcp
    runtime: nvidia
    ports:
      - "11434:11434"
    healthcheck:
      test: llama --version
    entrypoint: /root/entrypoint.sh
    volumes:
      - ./llama:/root/.llama
      - ./entrypoint.sh:/root/entrypoint.sh
    networks:
      - general

  solution:
    container_name: solution
    runtime: nvidia
    environment:
      __mode: "PROD"
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    dns:
      - "1.1.1.1"
    depends_on:
      - ollama
    command: [ "/bin/sh", "-c", "uvicorn app.__main__:app --host 0.0.0.0 --port 8000" ]
    networks:
      - general



networks:
  general:
    driver: bridge
